POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjVmN2RjMzk4MzEzNmZmMWM1NDI1YTg0ZSIsImlhdCI6MTYwMjIzMTI5MH0.WE8aWxP81asUsIeeYKoF8LW8zdoQUTBqr_W45tPJUYE

{
  "title": "Blog",
  "author": "B. Logger",
  "url": "https://www.google.com/",
  "likes": 0
}